<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1LV8K5I" failures="2" tests="21" name="com.practo.tests.TestCases" time="914.345" errors="0" timestamp="2021-03-24T17:58:28 IST" skipped="0">
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_001" time="10.006"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_002" time="25.981"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_003" time="19.478"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_004" time="28.072"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_005" time="26.996"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_006" time="64.261"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_007" time="82.089"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_008" time="218.915"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_009" time="48.127"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_010" time="18.796"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_011" time="29.750"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_012" time="37.023"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_013" time="16.334"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_014" time="17.473"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_015" time="33.380"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_016" time="45.307"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_017" time="33.380"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_018" time="36.903"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_019" time="44.692"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_020" time="40.455">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestCases.TC_FH_020(TestCases.java:499)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_FH_020 -->
  <system-out/>
  <testcase classname="com.practo.tests.TestCases" name="TC_FH_021" time="36.927">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestCases.TC_FH_021(TestCases.java:525)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_FH_021 -->
  <system-out/>
</testsuite> <!-- com.practo.tests.TestCases -->
